#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/node:8
#    steps:
#      - checkout
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "package.json" }}
#            - v1-dependencies-
#      - run: yarn install
#      - save_cache:
#          paths:
#            - node_modules
#          key: v1-dependencies-{{ checksum "package.json" }}
#      - run: yarn test

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: ls ./
      - run: pwd
      - run: echo working_directory
      - run: yarn install
      - run: yarn test
